# Atividade 1

# Exercício 1

In [ ]:
import numpy as np
import sympy as sp
import matplotlib.pyplot as plt

%matplotlib inline         

x = np.linspace(-4,4,50) 
y1 = (x+1)**2
y2=y1**(1/3)
y2=y2*(x-3)**2
plt.plot(x,y2)     

In [5]:
from sympy import *
x=symbols('x')
y1 = (x+1)**2
y2=y1**(1/3)
y2=y2*(x-3)**2
eq=y2*(x-3)**2
r=simplify(diff(eq,x))
print(r)

(x - 3)**3*(4.66666666666667*x + 2.0)*((x + 1)**2)**0.333333333333333/(x + 1)


In [6]:
from sympy import *
x=symbols('x')
y1 = (x+1)**2
y2=y1**(1/3)
y2=y2*(x-3)**2
eq=y2*(x-3)**2
r=simplify(diff(eq,x,3))
print(r)

(x**2 + 2*x + 1)**0.333333333333333*(45.6296296296296*x**4 - 78.2222222222223*x**3 - 224.0*x**2 + 63.9999999999999*x + 240.0)/(1.0*x**3 + 3.0*x**2 + 3.0*x + 1.0)


In [9]:
from sympy import*
import sympy as sp
x,y=symbols('x y')
y = sp.cbrt(x+1)**2*(x-3)**2
integrate(y,x)

3*(x - 3)**3*(x + 1)**(2/3)/11 + 3*(x - 3)**2*(x + 1)**(2/3)/11 - 72*(x - 3)*(x + 1)**(2/3)/55 + 432*(x + 1)**(2/3)/55

In [12]:
from sympy import*
import sympy as sp
x,y=symbols('x y')
y = sp.cbrt(x+1)**2*(x-3)**2
integrate(y,(x,-1,2))

504*3**(2/3)/55

# Exercício 2

In [13]:
from sympy import*
def calcula_f(x):
    return (x**2-2*x)/cos(x)

x=sqrt(5)
y=calcula_f(x)
print("resultado da função para x=%.1f é %.1f" %(x,y))

resultado da função para x=2.2 é -0.9


In [14]:
#definir os símbolos usados
x=symbols('x')
#definir a função
expr=(x**2-2*x)/cos(x)
#calcular o limite
r=limit(expr,x,9)
print("%.1f" %r)

-69.1


In [17]:
from sympy import *
x=symbols('x')
expr=(x**2-2*x)/cos(x)
r=simplify(diff(eq,x))
print(r)

(x - 3)**3*(4.66666666666667*x + 2.0)*((x + 1)**2)**0.333333333333333/(x + 1)


# Exercício 3

In [18]:
import numpy as np

A = np.array([[1,0,1],[1,2,3], [1,2,4]])
print('A=\n',A)
B = np.array([[3,1,4],[1,2,1], [3,1,1]])
print('B=\n',B)

A=
 [[1 0 1]
 [1 2 3]
 [1 2 4]]
B=
 [[3 1 4]
 [1 2 1]
 [3 1 1]]


In [19]:
determ = np.linalg.det( A )
print(determ)

2.0


In [20]:
inv = np.linalg.inv( B )
print(inv)

[[-0.06666667 -0.2         0.46666667]
 [-0.13333333  0.6        -0.06666667]
 [ 0.33333333 -0.         -0.33333333]]


In [21]:
print('\nObtendo a transposta')
b_transposta = B.T
print(b_transposta)
print(b_transposta.shape)


Obtendo a transposta
[[3 1 3]
 [1 2 1]
 [4 1 1]]
(3, 3)


In [22]:
D=np.dot(A,B)
print('D=\n',D)

D=
 [[ 6  2  5]
 [14  8  9]
 [17  9 10]]


In [24]:
A = np.zeros((6,3))
A[:] = np.array([1, 2, 3, 4, 5, 6]).reshape(6,1)

print(A)

[[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]
 [4. 4. 4.]
 [5. 5. 5.]
 [6. 6. 6.]]


In [23]:
E=A -4*B
print(E)

[[-11  -4 -15]
 [ -3  -6  -1]
 [-11  -2   0]]


# Exercício 4

In [27]:
A = np.zeros((6,3))
A[:] = np.array([1, 2, 3, 4, 5, 6]).reshape(6,1)

print(A)

[[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]
 [4. 4. 4.]
 [5. 5. 5.]
 [6. 6. 6.]]


# Exercícios 5

In [25]:
X = np.random.uniform(0,1,100).reshape(10,10)
print('Matriz randomica:\n',X)

soma_colunas = np.sum(X,axis=0)
print('As somas das colunas é:\n',soma_colunas)

print('A coluna com maior some é a ',np.argmax(soma_colunas))

Matriz randomica:
 [[0.82323119 0.23395624 0.77237082 0.6655305  0.96007817 0.82718184
  0.77811834 0.22913834 0.00590317 0.98067526]
 [0.78827609 0.55919761 0.77699459 0.00399249 0.70270144 0.37931889
  0.57798615 0.35216466 0.73125896 0.76386967]
 [0.39707287 0.67239291 0.41226092 0.25286083 0.14391485 0.63482054
  0.19073321 0.86644558 0.38365831 0.9414415 ]
 [0.66622475 0.91689393 0.25014984 0.34568902 0.23469065 0.29655785
  0.49887602 0.51721058 0.42956413 0.76922574]
 [0.58878581 0.16271538 0.84575684 0.14260364 0.75616608 0.29430905
  0.47828265 0.00473296 0.95961288 0.20582687]
 [0.02384413 0.58411393 0.96295881 0.8938885  0.03675547 0.4973911
  0.75296106 0.47016702 0.42154517 0.44462608]
 [0.21077395 0.8535817  0.64139343 0.8780894  0.0051108  0.14980847
  0.30671749 0.89568237 0.94984812 0.36603571]
 [0.60841666 0.15856933 0.03493206 0.18187134 0.3576653  0.47259209
  0.915192   0.24881008 0.5224409  0.151297  ]
 [0.09743312 0.05665992 0.21196221 0.52643957 0.6910488  0.957