In [26]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.metrics import r2_score, mean_squared_error
df = pd.read_csv("data/winequality-red.csv",) 
df.head(10)

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   
5            7.4              0.66         0.00             1.8      0.075   
6            7.9              0.60         0.06             1.6      0.069   
7            7.3              0.65         0.00             1.2      0.065   
8            7.8              0.58         0.02             2.0      0.073   
9            7.5              0.50         0.36             6.1      0.071   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   
5                 13.0                  40.0   0.9978  3.51       0.56   
6                 15.0                  59.0   0.9964  3.30       0.46   
7                 15.0                  21.0   0.9946  3.39       0.47   
8                  9.0                  18.0   0.9968  3.36       0.57   
9                 17.0                 102.0   0.9978  3.35       0.80   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5  
5      9.4        5  
6      9.4        5  
7     10.0        7  
8      9.5        7  
9     10.5        5

In [27]:
df = df.to_numpy() #Transforma o dataframe em numpy
y = df[:,-1] # coluna quality
x=df[:,0]# fixed acidity
correlacao = np.corrcoef(x, y)
print(correlacao)

[[1.         0.12405165]
 [0.12405165 1.        ]]


In [28]:
y = df[:,2] 
x=df[:,-5]
correlacao = np.corrcoef(x, y)
print(correlacao)

[[1.         0.36494718]
 [0.36494718 1.        ]]


In [29]:
y = df[:,-1] 
x=df[:,-2]
correlacao = np.corrcoef(x, y)
print(correlacao)

[[1.         0.47616632]
 [0.47616632 1.        ]]


In [30]:
y = df[:,-3] 
x=df[:,-4]
correlacao = np.corrcoef(x, y)
print(correlacao)

[[ 1.        -0.1966476]
 [-0.1966476  1.       ]]


In [31]:
y = df[:,-1] # coluna quality
x=df[:,0]# fixed acidity


In [32]:
import sympy as sy
import numpy as np
from sklearn.linear_model import LinearRegression
x = np.array(x)
x = x.reshape(-1, 1)
modelo = LinearRegression().fit(x, y)
print(modelo.intercept_)
print (modelo.coef_)

5.157321868924811
[0.05753864]


In [33]:
from sklearn.metrics import r2_score
R2 = r2_score(y, modelo.predict(x))
print('R2:', R2)

R2: 0.015388811647710554
